title: ForumRec
show_link_tools: true
description: >- # this means to ignore newlines until "baseurl:"
  A recommender providing users the questions they can answer best.
baseurl: "" # the subpath of your site, e.g. /blog
github_username:  jasrajjohl
contact_page: /docs/contact.html
github: [metadata]

# Build settings
theme: jekyll-theme-slate 
plugins:
  - jekyll-feed
